@@include('./_main.js')
@@include('./_header.js')
@@include('./_footer.js')
@@include('./_mainbanner.js')
@@include('./_advantages.js')
@@include('./_products.js')
@@include('./_catalog.js')
@@include('./_product-card.js')
@@include('./_cart.js')
@@include('./_order.js')
@@include('./_personal.js')
@@include('./_compare.js')
@@include('./_static.js')

